export enum RecipeCategory {
  APPETIZER = 'Appetizer',
  MAIN_COURSE = 'Main Course',
  DESSERT = 'Dessert',
  BEVERAGE = 'Beverage',
  SNACK = 'Snack',
  SOUP = 'Soup',
  SALAD = 'Salad',
  SIDE_DISH = 'Side Dish',
  VEGETARIAN = 'Vegetarian',
  VEGAN = 'Vegan',
  GLUTEN_FREE = 'Gluten Free',
  KETO = 'Keto',
  PALEO = 'Paleo',
}
